import fs from 'node:fs';
import { execFileSync } from 'node:child_process';
import path from 'node:path';
import { appendAudit } from './audit.js';
import { runAgentLoop } from './agent.js';
import { makeVerifier } from './tools.js';
import type { RunState, StepResult } from './types.js';

/**
 * THE FLYWHEEL — every run makes the runbook smarter.
 *
 * After execution, an agent diffs "what the runbook said" vs "what actually
 * happened" and appends an addendum to the markdown. Then it git-commits.
 * Runbooks that improve with every execution is the closing argument.
 */

const ADDENDUM_HEADER = (run: RunState) =>
  `\n\n---\n\n## 🩹 Execution addendum — ${run.startedAt}\n\n<!-- firerun-addendum: auto-generated by FIRSTRESPONDER; review before deleting -->\n\n- **Mode:** ${run.mode} → ${run.target}\n- **Run ID:** \`${run.runId}\`\n- **Outcome:** ${run.green ? '✅ completed end-to-end' : '🛑 halted (see deviations)'}\n`;

export async function writeAddendum(state: RunState): Promise<{ committed: boolean; addendumPath: string }> {
  const verifier = makeVerifier({ runId: state.runId, appUrl: '', dbUrl: '' });

  const stepSummaries = Object.values(state.results)
    .map((r: StepResult) => {
      const step = state.graph.steps.find(s => s.id === r.stepId)!;
      const toolCalls = r.transcript.filter(t => t.toolCalls?.length).reduce((n, t) => n + (t.toolCalls?.length ?? 0), 0);
      return `- ${r.stepId} [${step.type}] ${step.title} → ${r.status}${r.durationMs ? ` (${Math.round(r.durationMs / 100) / 10}s, ${toolCalls} tool calls)` : ''}${r.error ? ` — deviation: ${r.error.slice(0, 160)}` : ''}`;
    })
    .join('\n');

  const loop = await runAgentLoop({
    system: `You are the Runbook Addendum Writer. Given the transcript summary of a runbook execution, write 2-5 bullet points of what ACTUALLY happened that the runbook didn't predict: deviations, actual commands that worked, timings, edge cases. Be specific and terse. Use the report tool once with the final bullet list (plain markdown bullets, no headers). End with DONE.`,
    goal: `Runbook: ${state.graph.title}\nStep outcomes:\n${stepSummaries}\n\nWrite the addendum bullets now.`,
    ctx: verifier,
    maxIterations: 4,
    onToolCall: (name, args) => console.log(`      📚 FLYWHEEL → ${name} ${JSON.stringify(args).slice(0, 100)}`),
  });

  const bullets = loop.reason.replace(/DONE/gi, '').trim() || '- No significant deviations from the runbook as written.';

  const mdPath = path.resolve(state.graph.runbook);
  const original = fs.readFileSync(mdPath, 'utf8');
  const updated = original + ADDENDUM_HEADER(state) + bullets + '\n';
  fs.writeFileSync(mdPath, updated);
  appendAudit('addendum_written', { runbook: state.graph.runbook, runId: state.runId }, state.runId);
  console.log(`      📚 addendum appended to ${path.basename(mdPath)}`);

  let committed = false;
  try {
    execFileSync('git', ['add', path.basename(mdPath)], { cwd: path.dirname(mdPath) });
    execFileSync('git', ['commit', '-m', `runbook: addendum after ${state.mode.toLowerCase()} ${state.runId} (${state.graph.title})`], {
      cwd: path.dirname(mdPath),
    });
    committed = true;
    console.log(`      📚 git commit — the runbook just got smarter.`);
    appendAudit('addendum_committed', { runbook: state.graph.runbook }, state.runId);
  } catch {
    console.log(`      📚 (not a git repo — addendum saved but not committed)`);
  }
  return { committed, addendumPath: mdPath };
}
